spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Authentication
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
security:
  jwt:
    lifetime: 3600000
    key: c292656dc120ab4c995397dc8a145404084737f3b7b2ac11457345e84ea19664
  origin:
    gateway-secret: M9IzaWFV3lare8J2N8AVMtDVKlvsvwTZZBhEQ4GfGRtWlT7rsbo6oqsZSNuJCJM0uVGemKfbCwWGouRjqX9riVfELkUq5t69
    internal-secret: 69ce7f22993b4b61bec02e672655449fa61d2217e8b64337b7e0f71a6d49aa40780ae30053c1484f9085cbc7986fd264
  refresh:
    lifetime: 2592000000
server:
  port: 1812
  forward-headers-strategy: framework
services:
  profile-service:
    url: http://127.0.0.1:8001
springdoc:
  api-docs:
    path: /auth/v3/api-docs