spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
server:
  port: 1812
  forward-headers-strategy: framework
springdoc:
  api-docs:
    path: /auth/v3/api-docs
  swagger-ui:
    enabled: false