spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Authentication
    username: root
    password: root
token:
  lifetime: 3600000
  key: c292656dc120ab4c995397dc8a145404084737f3b7b2ac11457345e84ea19664
server:
  port: 1812
logging:
    level:
      root: DEBUG