spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:1812
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=0
            - id: profile-service
              uri: http://localhost:8001
              predicates:
                - Path=/api/v1/persons/**
              filters:
                - StripPrefix=0
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
rate-limiting:
  bucket4j:
    tokenCapacity: 3
    duration: 20s
security:
  jwt:
    key: c292656dc120ab4c995397dc8a145404084737f3b7b2ac11457345e84ea19664
  gateway:
    secret: M9IzaWFV3lare8J2N8AVMtDVKlvsvwTZZBhEQ4GfGRtWlT7rsbo6oqsZSNuJCJM0uVGemKfbCwWGouRjqX9riVfELkUq5t69
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
server:
  port: 8888