spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5430/Book
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    aws:

      s3:
        endpoint: http://localhost:9000
        path-style-access-enabled: true
        region: us-east-1
      credentials:
        access-key: minioadmin
        secret-key: minioadmin
    storage:
      bucket-name: pdf-bucket
      content-type: application/pdf
      destination: books/%s
      page-destination: /pages
      file-extension: .pdf
server:
  port: 8002
security:
  origin:
    gateway:
      secret: M9IzaWFV3lare8J2N8AVMtDVKlvsvwTZZBhEQ4GfGRtWlT7rsbo6oqsZSNuJCJM0uVGemKfbCwWGouRjqX9riVfELkUq5t69