spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5430/Book
    username: root
    password: root
server:
  port: 8002
security:
  origin:
    gateway:
      secret: M9IzaWFV3lare8J2N8AVMtDVKlvsvwTZZBhEQ4GfGRtWlT7rsbo6oqsZSNuJCJM0uVGemKfbCwWGouRjqX9riVfELkUq5t69