spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:postgresql://localhost:5431/Profile
    username: root
    password: root
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8001
  forward-headers-strategy: framework
resilience4j:
  circuitbreaker:
    instances:
      bookService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - com.bookhub.profileservice.exceptions.extensions.RemoteServiceException
          - com.bookhub.profileservice.exceptions.extensions.RemoteInternalServerErrorException
  retry:
    instances:
      bookService:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        exponential-max-wait-duration: 2s
        enable-randomized-wait: true
        randomized-wait-factor: 0.5
        retry-exceptions:
          - com.bookhub.profileservice.exceptions.extensions.RemoteInternalServerErrorException
        ignore-exceptions:
          - com.bookhub.profileservice.exceptions.extensions.RemoteServiceException
security:
  origin:
    gateway-secret: M9IzaWFV3lare8J2N8AVMtDVKlvsvwTZZBhEQ4GfGRtWlT7rsbo6oqsZSNuJCJM0uVGemKfbCwWGouRjqX9riVfELkUq5t69
    internal-secret: 69ce7f22993b4b61bec02e672655449fa61d2217e8b64337b7e0f71a6d49aa40780ae30053c1484f9085cbc7986fd264
services:
  book-service:
    url: http://127.0.0.1:8002
springdoc:
  api-docs:
    path: /profile/v3/api-docs
  show-login-endpoint: true
  model-and-view-allowed: true